import type { AppLocale, CatalogItem, CatalogStatus } from '@/lib/domain/types';

export const catalogCopy = {
  ko: {
    eyebrow: '우리 동네 책장',
    title: '다음 책을 발견해 보세요',
    subtitle: '이웃이 아끼는 책을 빌리고, 함께 읽는 즐거움을 나눠요.',
    results: (count: number) => `도서 ${count}권`,
    filter: '필터',
    filters: '도서 필터',
    filterHelp: '소유자, 대여 상태, 언어로 원하는 책을 빠르게 찾아보세요.',
    ownerFilter: '소유자',
    statusFilter: '대여 상태',
    languageFilter: '언어',
    allOwners: '모든 소유자',
    allStatuses: '모든 상태',
    allLanguages: '모든 언어',
    korean: '한국어',
    english: '영어',
    otherLanguage: '기타 언어',
    apply: '결과 보기',
    reset: '필터 초기화',
    clearSearch: '검색어 지우기',
    noResults: '조건에 맞는 책이 없어요',
    noResultsHelp: '검색어나 필터를 바꾸면 다른 책을 찾을 수 있어요.',
    clearAll: '검색과 필터 지우기',
    bookBy: (authors: string) => authors ? `${authors} 지음` : '저자 정보 없음',
    ownedBy: (name: string) => `${name}님의 책`,
    mine: '내 책',
    owner: '소유자',
    back: '도서 목록으로',
    details: '도서 정보',
    published: '출간',
    pages: '쪽',
    isbn: 'ISBN',
    language: '언어',
    condition: '책 상태',
    ownerNote: '소유자 메모',
    noOwnerNote: '추가 메모가 없어요.',
    likeNew: '새 책 같음',
    good: '좋음',
    wellLoved: '사용감 있음',
    edit: '내 도서 수정',
    editTitle: '내 도서 수정',
    editHelp: '표지, 책 상태와 대여자에게 보일 메모를 관리하세요.',
    replaceCover: '표지 사진 바꾸기',
    refreshCover: '더 선명한 온라인 표지 찾기',
    refreshingCover: '표지 찾는 중…',
    coverRefreshed: 'ISBN과 일치하는 새 표지로 바꿨어요.',
    coverRefreshFailed: '더 선명한 표지를 찾지 못했어요. 직접 찍은 사진을 사용할 수 있어요.',
    coverHelp: '선명한 정면 사진을 사용하세요. JPG, PNG, WebP · 최대 8MB',
    coverError: 'JPG, PNG, WebP 형식의 8MB 이하 이미지를 선택해 주세요.',
    coverUploadFailed: '표지 사진을 업로드하지 못했어요. 다시 시도해 주세요.',
    saving: '저장 중…',
    save: '저장',
    saved: '도서 정보를 저장했어요.',
    remove: '목록에서 삭제',
    removeTitle: '이 책을 삭제할까요?',
    removeHelp: '도서 목록에서 숨겨집니다. 이 작업은 이 화면에서 되돌릴 수 없어요.',
    removeBlocked: '대여 중인 책은 반납이 기록된 뒤 삭제할 수 있어요.',
    cancel: '취소',
    confirmRemove: '삭제',
    request: '대여 요청',
    requested: '소유자에게 요청을 보냈어요. 48시간 안에 답변이 없으면 자동 만료돼요.',
    cancelRequest: '대여 요청 취소',
    requestCanceled: '대여 요청을 취소했어요.',
    requestPending: '대여 요청을 기다리는 중이에요',
    requestPendingHelp: '소유자가 카카오톡 알림이나 앱에서 결정하면 알려드릴게요.',
    unavailable: '현재 대여할 수 없는 책이에요.',
    ownBook: '내 책은 대여 요청할 필요가 없어요.',
    returnBook: '반납 완료',
    returned: '반납을 기록했어요. 이제 다른 회원이 빌릴 수 있어요.',
    onLoanToYou: '내가 빌린 책',
    lentByYou: '내가 빌려준 책',
    borrowedBy: (name: string) => `${name}님이 대여 중`,
    pendingRequests: (count: number) => `대기 중인 요청 ${count}건`,
    missingTitle: '도서를 찾을 수 없어요',
    missingHelp: '목록으로 돌아가 다른 책을 선택해 주세요.',
  },
  en: {
    eyebrow: 'Your neighborhood shelf',
    title: 'Find your next read',
    subtitle: 'Borrow books your neighbors love and make reading a shared habit.',
    results: (count: number) => `${count} ${count === 1 ? 'book' : 'books'}`,
    filter: 'Filters',
    filters: 'Book filters',
    filterHelp: 'Narrow the catalog by owner, lending status, or language.',
    ownerFilter: 'Owner',
    statusFilter: 'Status',
    languageFilter: 'Language',
    allOwners: 'All owners',
    allStatuses: 'All statuses',
    allLanguages: 'All languages',
    korean: 'Korean',
    english: 'English',
    otherLanguage: 'Other language',
    apply: 'Show results',
    reset: 'Reset filters',
    clearSearch: 'Clear search',
    noResults: 'No books match',
    noResultsHelp: 'Try a different search or loosen one of your filters.',
    clearAll: 'Clear search and filters',
    bookBy: (authors: string) => authors ? `by ${authors}` : 'Author not listed',
    ownedBy: (name: string) => `Owned by ${name}`,
    mine: 'My book',
    owner: 'Owner',
    back: 'Back to catalog',
    details: 'Book details',
    published: 'Published',
    pages: 'pages',
    isbn: 'ISBN',
    language: 'Language',
    condition: 'Condition',
    ownerNote: 'Owner note',
    noOwnerNote: 'No additional note.',
    likeNew: 'Like new',
    good: 'Good',
    wellLoved: 'Well loved',
    edit: 'Edit my listing',
    editTitle: 'Edit my listing',
    editHelp: 'Update the cover, condition, and borrower-facing note.',
    replaceCover: 'Replace cover photo',
    refreshCover: 'Find a sharper online cover',
    refreshingCover: 'Finding cover…',
    coverRefreshed: 'Replaced it with a new cover matched to this ISBN.',
    coverRefreshFailed: 'We couldn’t find a sharper cover. You can use your own photo instead.',
    coverHelp: 'Use a sharp, straight-on photo. JPG, PNG, or WebP · up to 8 MB',
    coverError: 'Choose a JPG, PNG, or WebP image no larger than 8 MB.',
    coverUploadFailed: 'We couldn’t upload that cover. Please try again.',
    saving: 'Saving…',
    save: 'Save',
    saved: 'Book details saved.',
    remove: 'Remove from catalog',
    removeTitle: 'Remove this book?',
    removeHelp: 'It will be hidden from the catalog. This cannot be undone from this screen.',
    removeBlocked: 'A borrowed book can only be removed after its return is recorded.',
    cancel: 'Cancel',
    confirmRemove: 'Remove',
    request: 'Request to borrow',
    requested: 'Request sent. It will expire if the owner does not respond within 48 hours.',
    cancelRequest: 'Cancel request',
    requestCanceled: 'Borrow request canceled.',
    requestPending: 'Waiting for the owner',
    requestPendingHelp: 'We will let you know after the owner decides from KakaoTalk or the app.',
    unavailable: 'This book is not available to borrow right now.',
    ownBook: 'You do not need to request your own book.',
    returnBook: 'Mark returned',
    returned: 'Return recorded. Other members can borrow this book again.',
    onLoanToYou: 'Borrowed by you',
    lentByYou: 'Lent by you',
    borrowedBy: (name: string) => `Borrowed by ${name}`,
    pendingRequests: (count: number) => `${count} pending ${count === 1 ? 'request' : 'requests'}`,
    missingTitle: 'Book not found',
    missingHelp: 'Return to the catalog and choose another book.',
  },
} as const;

export function statusLabel(locale: AppLocale, status: CatalogStatus) {
  const labels = {
    ko: { available: '대여 가능', borrowed: '대여 중', archived: '목록에서 삭제됨' },
    en: { available: 'Available', borrowed: 'Borrowed', archived: 'Removed' },
  } as const;
  return labels[locale][status];
}

export function conditionLabel(locale: AppLocale, condition: CatalogItem['condition']) {
  const t = catalogCopy[locale];
  return condition === 'like-new' ? t.likeNew : condition === 'good' ? t.good : t.wellLoved;
}

export function languageLabel(locale: AppLocale, language: CatalogItem['edition']['language']) {
  const t = catalogCopy[locale];
  return language === 'ko' ? t.korean : language === 'en' ? t.english : t.otherLanguage;
}
